-- FEA: Audit ledger + revert/undo (change history for every owner-stamped table)
--
-- Records a row in disciplan.audit_log for every INSERT/UPDATE/DELETE on any
-- table carrying owner + household_id columns. Captures the full before/after
-- snapshot, who made the change (resolved from the JWT via profiles), and the
-- transaction id (txid_current) so all rows touched by a single REST request
-- (e.g. a 300-row import, or an edit + its counter-leg) share one group and can
-- be undone together.
--
-- Reverting issues normal DML, so the inverse change is itself audited — undo is
-- re-doable. Permission to revert mirrors RLS can_write(): admins for the whole
-- household, members for their own rows.
--
-- This is forward-looking: only changes made after this migration are recorded.

-- ── 1. Audit table ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS disciplan.audit_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name    TEXT        NOT NULL,
  row_id        TEXT,                       -- affected row's id (TEXT: accounts use slug ids)
  op            TEXT        NOT NULL CHECK (op IN ('INSERT','UPDATE','DELETE')),
  old_data      JSONB,                      -- full OLD row (UPDATE/DELETE)
  new_data      JSONB,                      -- full NEW row (INSERT/UPDATE)
  changed_cols  TEXT[],                     -- columns that actually changed (UPDATE)
  owner         TEXT,                       -- row's owner
  household_id  BIGINT,                     -- row's household
  actor_uid     UUID,                       -- auth.uid() of who made the change
  actor         TEXT,                       -- resolved label (profiles.owner, else db role)
  txid          BIGINT      NOT NULL,       -- groups one operation (one REST request)
  reverted_at   TIMESTAMPTZ,                -- set when this entry has been reverted
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_log_table_row_idx ON disciplan.audit_log (table_name, row_id);
CREATE INDEX IF NOT EXISTS audit_log_created_idx   ON disciplan.audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS audit_log_txid_idx      ON disciplan.audit_log (txid);
CREATE INDEX IF NOT EXISTS audit_log_household_idx ON disciplan.audit_log (household_id, created_at DESC);

-- Clients read their household's history; they never write it directly (the
-- trigger and revert RPCs run SECURITY DEFINER and bypass RLS).
GRANT SELECT ON disciplan.audit_log TO authenticated;
GRANT ALL    ON disciplan.audit_log TO service_role;

ALTER TABLE disciplan.audit_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "audit_log_select" ON disciplan.audit_log;
CREATE POLICY "audit_log_select" ON disciplan.audit_log
  FOR SELECT TO authenticated
  USING (household_id IS NULL OR household_id = disciplan.my_household());

-- ── 2. Generic trigger function ──────────────────────────────────────────
CREATE OR REPLACE FUNCTION disciplan.fn_audit()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = disciplan, public AS $$
DECLARE
  v_new     JSONB := CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW) END;
  v_old     JSONB := CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END;
  v_changed TEXT[];
  v_actor   TEXT;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    SELECT array_agg(k) INTO v_changed
    FROM jsonb_object_keys(v_new) AS k
    WHERE k <> 'updated_at' AND (v_new -> k) IS DISTINCT FROM (v_old -> k);
    -- Skip no-op / updated_at-only writes so the log stays meaningful.
    IF v_changed IS NULL OR array_length(v_changed, 1) IS NULL THEN
      RETURN NULL;
    END IF;
  END IF;

  v_actor := COALESCE(
    (SELECT owner FROM disciplan.profiles WHERE auth_uid = auth.uid()),
    NULLIF(current_user, '')
  );

  INSERT INTO disciplan.audit_log (
    table_name, row_id, op, old_data, new_data, changed_cols,
    owner, household_id, actor_uid, actor, txid
  ) VALUES (
    TG_TABLE_NAME,
    COALESCE(v_new ->> 'id', v_old ->> 'id'),
    TG_OP,
    v_old, v_new, v_changed,
    COALESCE(v_new ->> 'owner', v_old ->> 'owner'),
    NULLIF(COALESCE(v_new ->> 'household_id', v_old ->> 'household_id'), '')::BIGINT,
    auth.uid(),
    v_actor,
    txid_current()
  );
  RETURN NULL;
END;
$$;

-- ── 3. Attach to every base table with owner + household_id (except audit_log) ─
DO $$
DECLARE t TEXT;
BEGIN
  FOR t IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.tables tb
      ON tb.table_schema = c.table_schema AND tb.table_name = c.table_name
     AND tb.table_type = 'BASE TABLE'
    WHERE c.table_schema = 'disciplan'
      AND c.column_name = 'owner'
      AND c.table_name <> 'audit_log'
      AND EXISTS (
        SELECT 1 FROM information_schema.columns c2
        WHERE c2.table_schema = 'disciplan'
          AND c2.table_name = c.table_name
          AND c2.column_name = 'household_id'
      )
    GROUP BY c.table_name
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON disciplan.%I', 'zaudit_' || t, t);
    EXECUTE format(
      'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON disciplan.%I FOR EACH ROW EXECUTE FUNCTION disciplan.fn_audit()',
      'zaudit_' || t, t);
  END LOOP;
END $$;

-- ── 4. Revert a single audit entry (reverses one row change) ──────────────
CREATE OR REPLACE FUNCTION disciplan.revert_audit_entry(p_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = disciplan, public AS $$
DECLARE
  r       disciplan.audit_log;
  v_cols  TEXT[];
  v_pk    TEXT[];
  v_set   TEXT;
  v_match TEXT;
BEGIN
  SELECT * INTO r FROM disciplan.audit_log WHERE id = p_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'audit entry % not found', p_id; END IF;
  IF r.reverted_at IS NOT NULL THEN RAISE EXCEPTION 'audit entry % already reverted', p_id; END IF;
  IF NOT disciplan.can_write(r.owner, r.household_id) THEN
    RAISE EXCEPTION 'not permitted to revert change to % owned by %', r.table_name, r.owner;
  END IF;

  SELECT array_agg(column_name::TEXT ORDER BY ordinal_position) INTO v_cols
  FROM information_schema.columns
  WHERE table_schema = 'disciplan' AND table_name = r.table_name;

  SELECT array_agg(a.attname ORDER BY x.ord) INTO v_pk
  FROM pg_index i
  CROSS JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS x(attnum, ord)
  JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = x.attnum
  WHERE i.indrelid = format('disciplan.%I', r.table_name)::regclass AND i.indisprimary;

  IF v_pk IS NULL THEN
    RAISE EXCEPTION 'cannot revert %: table has no primary key', r.table_name;
  END IF;

  SELECT string_agg(format('t.%I = s.%I', c, c), ' AND ') INTO v_match FROM unnest(v_pk) AS c;

  IF r.op = 'INSERT' THEN
    -- The row was created; undo by deleting it.
    EXECUTE format(
      'DELETE FROM disciplan.%I t USING (SELECT (jsonb_populate_record(NULL::disciplan.%I, $1)).*) s WHERE %s',
      r.table_name, r.table_name, v_match) USING r.new_data;
  ELSIF r.op = 'DELETE' THEN
    -- The row was removed; undo by re-inserting it exactly.
    EXECUTE format(
      'INSERT INTO disciplan.%I SELECT (jsonb_populate_record(NULL::disciplan.%I, $1)).*',
      r.table_name, r.table_name) USING r.old_data;
  ELSE -- UPDATE
    SELECT string_agg(format('%I = s.%I', c, c), ', ') INTO v_set FROM unnest(v_cols) AS c;
    EXECUTE format(
      'UPDATE disciplan.%I t SET %s FROM (SELECT (jsonb_populate_record(NULL::disciplan.%I, $1)).*) s WHERE %s',
      r.table_name, v_set, r.table_name, v_match) USING r.old_data;
  END IF;

  UPDATE disciplan.audit_log SET reverted_at = now() WHERE id = p_id;
  RETURN jsonb_build_object('id', r.id, 'table', r.table_name, 'op', r.op, 'row_id', r.row_id);
END;
$$;

-- ── 5. Revert a whole operation (all rows sharing one txid) ───────────────
CREATE OR REPLACE FUNCTION disciplan.revert_operation(p_txid BIGINT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = disciplan, public AS $$
DECLARE rec RECORD; v_count INT := 0;
BEGIN
  FOR rec IN
    SELECT id FROM disciplan.audit_log
    WHERE txid = p_txid AND reverted_at IS NULL
    ORDER BY id DESC
  LOOP
    PERFORM disciplan.revert_audit_entry(rec.id);
    v_count := v_count + 1;
  END LOOP;
  RETURN jsonb_build_object('txid', p_txid, 'reverted', v_count);
END;
$$;

-- ── 6. Undo the caller's most recent operation ────────────────────────────
CREATE OR REPLACE FUNCTION disciplan.undo_last()
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = disciplan, public AS $$
DECLARE v_actor TEXT; v_txid BIGINT;
BEGIN
  v_actor := (SELECT owner FROM disciplan.profiles WHERE auth_uid = auth.uid());
  SELECT txid INTO v_txid
  FROM disciplan.audit_log
  WHERE reverted_at IS NULL AND (v_actor IS NULL OR actor = v_actor)
  ORDER BY created_at DESC, id DESC
  LIMIT 1;
  IF v_txid IS NULL THEN RETURN jsonb_build_object('reverted', 0); END IF;
  RETURN disciplan.revert_operation(v_txid);
END;
$$;

GRANT EXECUTE ON FUNCTION disciplan.revert_audit_entry(BIGINT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION disciplan.revert_operation(BIGINT)   TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION disciplan.undo_last()                TO authenticated, service_role;
