-- FEA: Persist Income Statement budget targets (% of income) for app + newsletter agent.
-- Household-scoped (one target set per household per year). Exposed read-only via insight_ro.

CREATE TABLE IF NOT EXISTS disciplan.budget_targets (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id  BIGINT NOT NULL REFERENCES disciplan.households(id),
  owner         TEXT,
  year          INT NOT NULL,
  category_id   TEXT NOT NULL,
  pct_of_income NUMERIC NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (household_id, year, category_id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON disciplan.budget_targets TO authenticated;
GRANT ALL ON disciplan.budget_targets TO service_role;
GRANT USAGE, SELECT ON SEQUENCE disciplan.budget_targets_id_seq TO authenticated;
GRANT ALL ON SEQUENCE disciplan.budget_targets_id_seq TO service_role;

ALTER TABLE disciplan.budget_targets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "budget_targets_all" ON disciplan.budget_targets;
CREATE POLICY "budget_targets_all" ON disciplan.budget_targets
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS budget_targets_household_year_idx
  ON disciplan.budget_targets (household_id, year);

-- Seed historical targets (from js/constants.js BUDGET_TARGETS) for the seeded household.
-- 2026 copies 2025 so the current year has explicit rows.
DO $$
DECLARE
  hid BIGINT;
BEGIN
  SELECT id INTO hid FROM disciplan.households ORDER BY id LIMIT 1;
  IF hid IS NULL THEN
    RAISE NOTICE 'budget_targets seed skipped: no household';
    RETURN;
  END IF;
  EXECUTE format('ALTER TABLE disciplan.budget_targets ALTER COLUMN household_id SET DEFAULT %L', hid);

  INSERT INTO disciplan.budget_targets (household_id, owner, year, category_id, pct_of_income)
  SELECT hid, 'mark', v.year, v.category_id, v.pct
  FROM (VALUES
    (2019,'entertainment',4),(2019,'accommodation',0),(2019,'games',0),(2019,'food',6),(2019,'groceries',2.5),(2019,'restaurant',3.5),(2019,'home',25),(2019,'rent',23.5),(2019,'furniture',1.5),(2019,'health',2.5),(2019,'personal',3),(2019,'clothes',1.5),(2019,'tech',1.5),(2019,'transportation',2.5),(2019,'utilities',1.5),(2019,'financial',0.5),(2019,'other',1),(2019,'_expenses',46),(2019,'_savings',54),
    (2020,'entertainment',2),(2020,'accommodation',0),(2020,'games',0),(2020,'food',6),(2020,'groceries',2.5),(2020,'restaurant',3.5),(2020,'home',25),(2020,'rent',23.5),(2020,'furniture',1.5),(2020,'health',2.5),(2020,'personal',3),(2020,'clothes',1.5),(2020,'tech',1.5),(2020,'transportation',1.5),(2020,'utilities',1.5),(2020,'financial',0.5),(2020,'other',1),(2020,'_expenses',43),(2020,'_savings',57),
    (2021,'entertainment',4),(2021,'accommodation',0),(2021,'games',0),(2021,'food',8),(2021,'groceries',3.5),(2021,'restaurant',4.5),(2021,'home',25),(2021,'rent',23.5),(2021,'furniture',1.5),(2021,'health',6),(2021,'personal',3),(2021,'clothes',1.5),(2021,'tech',1.5),(2021,'transportation',2.5),(2021,'utilities',1.5),(2021,'financial',0.5),(2021,'other',1),(2021,'_expenses',51.5),(2021,'_savings',48.5),
    (2022,'entertainment',5),(2022,'accommodation',0),(2022,'games',0),(2022,'food',7),(2022,'groceries',3),(2022,'restaurant',4),(2022,'home',21.5),(2022,'rent',20),(2022,'furniture',1.5),(2022,'health',3),(2022,'personal',2),(2022,'clothes',1),(2022,'tech',1),(2022,'transportation',4),(2022,'utilities',2),(2022,'financial',0),(2022,'other',1),(2022,'_expenses',45.5),(2022,'_savings',54.5),
    (2023,'entertainment',8),(2023,'accommodation',0),(2023,'games',0),(2023,'food',7),(2023,'groceries',2),(2023,'restaurant',5),(2023,'home',21),(2023,'rent',20),(2023,'furniture',1),(2023,'health',4),(2023,'personal',2),(2023,'clothes',1),(2023,'tech',1),(2023,'transportation',5),(2023,'utilities',2),(2023,'financial',0),(2023,'other',1),(2023,'_expenses',50),(2023,'_savings',50),
    (2024,'entertainment',7),(2024,'accommodation',0),(2024,'games',0),(2024,'food',6),(2024,'groceries',1),(2024,'restaurant',5),(2024,'home',19),(2024,'rent',18),(2024,'furniture',1),(2024,'health',4),(2024,'personal',3),(2024,'clothes',1.5),(2024,'tech',1.5),(2024,'transportation',5),(2024,'utilities',2),(2024,'financial',0),(2024,'other',1),(2024,'_expenses',47),(2024,'_savings',53),
    (2025,'entertainment',7),(2025,'accommodation',0),(2025,'games',0),(2025,'food',6),(2025,'groceries',1),(2025,'restaurant',5),(2025,'home',19),(2025,'rent',18),(2025,'furniture',1),(2025,'health',4),(2025,'personal',3),(2025,'clothes',1.5),(2025,'tech',1.5),(2025,'transportation',5),(2025,'utilities',2),(2025,'financial',0),(2025,'other',1),(2025,'_expenses',47),(2025,'_savings',53),
    (2026,'entertainment',7),(2026,'accommodation',0),(2026,'games',0),(2026,'food',6),(2026,'groceries',1),(2026,'restaurant',5),(2026,'home',19),(2026,'rent',18),(2026,'furniture',1),(2026,'health',4),(2026,'personal',3),(2026,'clothes',1.5),(2026,'tech',1.5),(2026,'transportation',5),(2026,'utilities',2),(2026,'financial',0),(2026,'other',1),(2026,'_expenses',47),(2026,'_savings',53)
  ) AS v(year, category_id, pct)
  ON CONFLICT (household_id, year, category_id) DO NOTHING;
END $$;

-- Agent SQL tool: owner-scoped read view (fail closed when GUC unset).
CREATE OR REPLACE VIEW insight_ro.budget_targets AS
SELECT year, category_id, pct_of_income
  FROM disciplan.budget_targets bt
 WHERE bt.household_id IN (
   SELECT p.household_id FROM disciplan.profiles p
    WHERE p.owner = current_setting('disciplan.insight_owner', true)
 );
