-- FEA-29C: Splitwise write-back — label -> friend mapping.
--
-- In Disciplan the reimbursed "person" is just a free-text label (e.g. "Shilpa"),
-- but Splitwise's create_expense needs a real friend user_id. This table stores
-- the one-time choice the user makes in the reimburse form's friend picker, so a
-- given person label resolves to a Splitwise friend without re-picking each time.

CREATE TABLE IF NOT EXISTS disciplan.splitwise_friend_map (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner        TEXT,
  household_id BIGINT,
  person_label TEXT NOT NULL,              -- normalized Disciplan person label (lowercased)
  sw_user_id   BIGINT NOT NULL,            -- Splitwise friend user id
  sw_name      TEXT,                       -- display name for the UI
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (owner, person_label)
);

-- Explicit grants (defense vs Supabase Oct 30, 2026 auto-grant removal)
GRANT SELECT, INSERT, UPDATE, DELETE ON disciplan.splitwise_friend_map TO authenticated;
GRANT ALL ON disciplan.splitwise_friend_map TO service_role;
GRANT USAGE, SELECT ON SEQUENCE disciplan.splitwise_friend_map_id_seq TO authenticated;
GRANT ALL ON SEQUENCE disciplan.splitwise_friend_map_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS idx_splitwise_friend_map_owner
  ON disciplan.splitwise_friend_map (owner, person_label);

-- Default household_id to the seeded household so an un-stamped insert still
-- appears in the Combined view (mirrors 20260620000001 / 20260625000001).
DO $$
DECLARE hid BIGINT;
BEGIN
  SELECT id INTO hid FROM disciplan.households ORDER BY id LIMIT 1;
  IF hid IS NOT NULL THEN
    EXECUTE format('ALTER TABLE disciplan.splitwise_friend_map ALTER COLUMN household_id SET DEFAULT %L', hid);
  END IF;
END $$;

ALTER TABLE disciplan.splitwise_friend_map ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "splitwise_friend_map_all" ON disciplan.splitwise_friend_map;
CREATE POLICY "splitwise_friend_map_all" ON disciplan.splitwise_friend_map
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
