-- FEA: Multi-user households (phase 1 schema foundation)
--
-- Adds a `households` grouping + a `profiles` map (auth user -> owner) and
-- stamps every user-data table with `owner` (text) + `household_id` (bigint).
-- Existing rows are backfilled to owner='mark' in the seeded household, so the
-- app behaves identically until single-person views are used.
--
-- Security note: RLS policies remain permissive (USING(true)) for now. The
-- columns added here make a future per-household / per-owner RLS tightening a
-- policy-only change (see plan Phase 6). No RLS is enforced yet.
--
-- ⚠ MANUAL STEP (cannot be done in plain SQL):
--   Create Shilpa's Supabase auth user (Dashboard → Authentication → Add user,
--   with her email + password) BEFORE running this migration so the section 5
--   profiles seed can match her. If you run the migration first, just re-run the
--   section 5 INSERT afterwards — it is idempotent. Mark's user already exists.

-- ── 1. Households + profiles ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS disciplan.households (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS disciplan.profiles (
  auth_uid     UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  owner        TEXT NOT NULL,
  household_id BIGINT NOT NULL REFERENCES disciplan.households(id),
  display_name TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Explicit grants (defense vs Supabase Oct 30, 2026 auto-grant removal)
GRANT SELECT, INSERT, UPDATE, DELETE ON disciplan.households TO authenticated;
GRANT ALL ON disciplan.households TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON disciplan.profiles   TO authenticated;
GRANT ALL ON disciplan.profiles   TO service_role;

ALTER TABLE disciplan.households ENABLE ROW LEVEL SECURITY;
ALTER TABLE disciplan.profiles   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "households_all" ON disciplan.households;
CREATE POLICY "households_all" ON disciplan.households
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "profiles_all" ON disciplan.profiles;
CREATE POLICY "profiles_all" ON disciplan.profiles
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── 2. Seed the household ────────────────────────────────────────────────
INSERT INTO disciplan.households (name)
SELECT 'Household'
WHERE NOT EXISTS (SELECT 1 FROM disciplan.households);

-- ── 3. Add owner + household_id to every user-data table ─────────────────
-- household_id defaults to the seeded household so any un-stamped insert still
-- appears in the Combined (household) view. owner is stamped by the app on
-- write; legacy rows are backfilled below.
DO $$
DECLARE
  hid  BIGINT;
  t    TEXT;
  tbls TEXT[] := ARRAY[
    'transactions','accounts','balance_snapshots','tags',
    'cashback_redemptions','cashback_cards',
    'investment_accounts','investment_symbols','investment_lots',
    'investment_price_history',
    'preferences','pending_imports','group_overrides'
  ];
BEGIN
  SELECT id INTO hid FROM disciplan.households ORDER BY id LIMIT 1;

  FOREACH t IN ARRAY tbls LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'disciplan' AND table_name = t
    ) THEN
      EXECUTE format('ALTER TABLE disciplan.%I ADD COLUMN IF NOT EXISTS owner TEXT', t);
      EXECUTE format('ALTER TABLE disciplan.%I ADD COLUMN IF NOT EXISTS household_id BIGINT', t);
      EXECUTE format('UPDATE disciplan.%I SET owner = ''mark'' WHERE owner IS NULL', t);
      EXECUTE format('UPDATE disciplan.%I SET household_id = %L WHERE household_id IS NULL', t, hid);
      EXECUTE format('ALTER TABLE disciplan.%I ALTER COLUMN household_id SET DEFAULT %L', t, hid);
    END IF;
  END LOOP;
END $$;

-- ── 4. Indexes for owner/household filtering on the hot table ─────────────
CREATE INDEX IF NOT EXISTS idx_transactions_household_owner
  ON disciplan.transactions (household_id, owner);
CREATE INDEX IF NOT EXISTS idx_transactions_owner_date
  ON disciplan.transactions (owner, date);

-- ── 5. Seed profiles (idempotent; needs both auth users to exist) ────────
-- Maps each Supabase auth user to an owner + the seeded household. Safe to
-- re-run. Rows for emails that do not yet exist as auth users are skipped.
INSERT INTO disciplan.profiles (auth_uid, owner, household_id, display_name)
SELECT u.id, v.owner, h.id, v.display_name
FROM (VALUES
  ('mark.q.ren2020@gmail.com',   'mark',   'Mark'),
  ('shilpakancharla18@gmail.com', 'shilpa', 'Shilpa')
) AS v(email, owner, display_name)
JOIN auth.users u ON lower(u.email) = lower(v.email)
CROSS JOIN (SELECT id FROM disciplan.households ORDER BY id LIMIT 1) h
ON CONFLICT (auth_uid) DO UPDATE
  SET owner = EXCLUDED.owner,
      household_id = EXCLUDED.household_id,
      display_name = EXCLUDED.display_name;

-- ── 6. Cross-person reimbursement proposals (plan Phase 5) ───────────────
CREATE TABLE IF NOT EXISTS disciplan.pending_shared_txns (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id  BIGINT NOT NULL REFERENCES disciplan.households(id),
  from_owner    TEXT NOT NULL,
  to_owner      TEXT NOT NULL,
  proposed_txn  JSONB NOT NULL,
  source_txn_id BIGINT,
  status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_pending_shared_to_status
  ON disciplan.pending_shared_txns (to_owner, status);

GRANT SELECT, INSERT, UPDATE, DELETE ON disciplan.pending_shared_txns TO authenticated;
GRANT ALL ON disciplan.pending_shared_txns TO service_role;

ALTER TABLE disciplan.pending_shared_txns ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pending_shared_txns_all" ON disciplan.pending_shared_txns;
CREATE POLICY "pending_shared_txns_all" ON disciplan.pending_shared_txns
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
