-- FEA: Cashback metadata migration (Phase 3)
-- Move cashback card metadata from hardcoded JS constants into DB.

CREATE TABLE IF NOT EXISTS cashback_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL,
  annual_fee_usd NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (annual_fee_usd >= 0),
  points_balance BIGINT NOT NULL DEFAULT 0 CHECK (points_balance >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cashback_cards_active_sort
  ON cashback_cards (is_active, sort_order, name);

INSERT INTO cashback_cards (name, color, annual_fee_usd, points_balance, is_active, sort_order)
VALUES
  ('AMEX Rose Gold', '#E07A5F', 1075, 123884, TRUE, 1),
  ('Chase United', '#4A6FA5', 345, 0, TRUE, 2),
  ('Chase Sapphire', '#3D405B', 985, 8507, TRUE, 3),
  ('Aeroplan', '#D4A373', 0, 140992, TRUE, 4),
  ('Bilt', '#81B29A', 0, 49752, TRUE, 5),
  ('Capital One', '#CB997E', 95, 0, FALSE, 6),
  ('Rakuten', '#F2CC8F', 0, 0, TRUE, 7),
  ('Uber', '#9B8EA0', 0, 0, FALSE, 8),
  ('Venmo Credit', '#6B9AC4', 0, 0, TRUE, 9),
  ('AMEX', '#264653', 90, 0, FALSE, 10),
  ('Chase Aeroplan', '#5B8DB8', 190, 0, FALSE, 11),
  ('TD Visa', '#8B687F', 0, 0, TRUE, 12),
  ('Scotiabank', '#E9C46A', 0, 0, FALSE, 13),
  ('Apple', '#7FB3D8', 0, 0, TRUE, 14),
  ('Flying Blue', '#52556E', 0, 0, FALSE, 15),
  ('Venmo', '#A8DADC', 0, 0, TRUE, 16)
ON CONFLICT (name) DO UPDATE
SET
  color = EXCLUDED.color,
  annual_fee_usd = EXCLUDED.annual_fee_usd,
  points_balance = EXCLUDED.points_balance,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

-- RLS: authenticated-only CRUD (matches pending_imports pattern).
ALTER TABLE cashback_cards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "cashback_cards_select" ON cashback_cards;
CREATE POLICY "cashback_cards_select" ON cashback_cards
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "cashback_cards_insert" ON cashback_cards;
CREATE POLICY "cashback_cards_insert" ON cashback_cards
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "cashback_cards_update" ON cashback_cards;
CREATE POLICY "cashback_cards_update" ON cashback_cards
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "cashback_cards_delete" ON cashback_cards;
CREATE POLICY "cashback_cards_delete" ON cashback_cards
  FOR DELETE TO authenticated USING (true);
