-- Follow-up questions asked in reply to a daily newsletter.
--
-- When Mark replies to an insight email with a question ("is this net accrual?",
-- "why only focus on health?", "what's the YoY rate?"), the inbound-email handler
-- records it here as 'pending'. The NEXT day's newsletter reads pending rows,
-- answers the genuine questions in a dedicated "Following up" section (using the
-- read-only query tool to fetch whatever data it needs), and marks them answered.

CREATE TABLE IF NOT EXISTS disciplan.insight_followups (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- The newsletter the question was asked about.
  source_log_id       BIGINT REFERENCES disciplan.insight_log(id) ON DELETE SET NULL,
  source_insight_type TEXT,
  question            TEXT NOT NULL,
  status              TEXT NOT NULL DEFAULT 'pending',   -- pending | answered
  -- Set when a later newsletter responds.
  answered_in_log_id  BIGINT REFERENCES disciplan.insight_log(id) ON DELETE SET NULL,
  answer              TEXT,
  answered_at         TIMESTAMPTZ,
  CONSTRAINT insight_followups_status_chk CHECK (status IN ('pending','answered'))
);

CREATE INDEX IF NOT EXISTS insight_followups_status_idx
  ON disciplan.insight_followups (status, created_at DESC);

-- Explicit grants (defense vs Supabase Oct 30, 2026 auto-grant removal).
GRANT SELECT, INSERT, UPDATE, DELETE ON disciplan.insight_followups TO authenticated;
GRANT ALL ON disciplan.insight_followups TO service_role;

ALTER TABLE disciplan.insight_followups ENABLE ROW LEVEL SECURITY;

-- Single-recipient newsletter infra (mirrors insight_log / principles_pending):
-- any authenticated household member may read/manage. The edge functions use the
-- service role and bypass RLS.
CREATE POLICY "insight_followups_all" ON disciplan.insight_followups
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
